### ISSUE TITLE
เพิ่ม code สำหรับการทำ benchmark ของ framework

### ISSUE THREAD

**Issue by up1** [goragod/somtum#1]
น่าจะเพิ่ม code ของการทำ performance testing ด้วยว่าทำอย่างไร หรือใช้เครื่องอะไรอย่างไรนะครับ
เพื่อทำให้คนที่เข้ามาช่วย contributed เอาไว้ทดสอบครับ
น่าจะมีประโยชน์สำหรับการปรับปรุงประสิทธิภาพของการทำงาน

ยกตัวอย่างเช่น
http://www.phpbenchmarks.com/en/
https://github.com/kenjis/php-framework-benchmark

**Comment by goragodwiriya** [comment]
มีครับ https://github.com/goragod/php-framework-benchmark
และในคู่มือของ https://github.com/kenjis/php-framework-benchmark ก็มีบอกวิธี benchmark ไว้ให้ครับ ผมก็ Fork มาจากอันนี้แหละ

ออฝากอนุมัติโพสต์ในกลุ่มด้วยนะครับ ไหนๆก็ทักมาแล้ว
